name: Flatpak Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged

    steps:
      - uses: actions/checkout@v3

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: network-scanner.flatpak
          manifest-path: in.netroy.network-scanner.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v2
        with:
          name: Flatpak Bundle
          path: network-scanner.flatpak

      # TODO: auto publish to flathub
